### ISSUE TITLE
add github button to index page

### ISSUE THREAD

**Issue by scbrown** [voluntaryist/site#4]
add github button to index page to let people know we're here.

**Comment by scbrown** [comment]
![github_button](https://cloud.githubusercontent.com/assets/6656238/9979286/2d06af62-5f33-11e5-9485-330055105c9e.png)

I've got two different samples here, one is a link on the left hand side of the page and the other is next to the social media icons on the top right of the page. addthis.com doesn't have a github button to add, so it's not integrated with them. Let me know which you like best.

**Comment by dscotese** [comment]
Carl and I prefer the one next to Facebook.  I liked the other one first, but Carl asked how many people will know what it's for and that got me thinking that "Contribute" is too similar to "Donate" - along with every other simple addition to the left-menu that we could use to get the viewer to understand what the icon is for.  On the right, they will either know "Oh! Github, Cool!" or they will hover, which will give a tooltip.  "Contribute to the website through Github" would work if you don't have a better one.

**Comment by dscotese** [comment]
You can see what I did.  Let me know if it could be done better.

In relation to using GH, I updated another file, toc.html (with the Table
of Contents for Issue 170), but haven't committed it to the website
branch.  I was about to, but figured it's ok if someone clones the project
without that change because Issue 170 is for 2016 (3rd Quarter!).  When I
push my local changes (to my local website branch), I push it to the remote
master and website (on GH).  This means that I've verified that it's live
and I'm making it available to anyone that wants to clone the project.

On Sat, Sep 19, 2015 at 10:04 PM, Steve Brown notifications@github.com
wrote:

> Assigned #4 https://github.com/voluntaryist/site/issues/4 to @dscotese
> https://github.com/dscotese.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/voluntaryist/site/issues/4#event-414081497.

## 

I like to provide some work at no charge to prove my value. Do you need a
techie?
I own Litmocracy http://www.litmocracy.com and Meme Racing
http://www.memeracing.net (in alpha).
I'm the webmaster for The Voluntaryist http://www.voluntaryist.com which
now accepts Bitcoin.
I also code for The Dollar Vigilante http://dollarvigilante.com/.
"He ought to find it more profitable to play by the rules" - Satoshi
Nakamoto
